/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mrflixter;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Rectangle;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneLayout;
import static mrflixter.Database.con;

/**
 *
 * @author Sridaran
 */
public class MainMenu extends javax.swing.JFrame {

   // private final ArrayList<User> userList = new ArrayList<User>(
    //               new User("admin", "admin", "admin@mail.com", "Admininistrator"),
    //             new User("user1", "1234", "user1@mail.com", "Firstname Lastname")
    //   )
    //   );
    private final ArrayList<Movie> movies = new ArrayList<Movie>(
            Arrays.asList(
                    new Movie("Comedy", "Movie 1", 3),
                    new Movie("Comedy", "Movie 2", 6),
                    new Movie("Romance", "Movie 3", 2),
                    new Movie("Thriller", "Movie 4", 8),
                    new Movie("Horror", "Movie 5", 4),
                    new Movie("Horror", "Movie 5", 4),
                    new Movie("Horror", "Movie 5", 4),
                    new Movie("Horror", "Movie 6", 7)
            )
    );

    private User user;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        initiateMoviesList();
    }

    public MainMenu(User u) {

        initComponents();
        if (null != u) {
            user = u;
            LblWelcome.setText("Welcome " + u.getFullName());
        }
        initiateMoviesList();
    }

    public void initiateMoviesList() {
        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout());
        add(panel, BorderLayout.CENTER);
        panel.setSize(800, 300);
        panel.setLocation(0, 100);
        panel.setAutoscrolls(true);
        panel.setPreferredSize(new Dimension(800, 300));

        for (int i = 0; i < movies.size(); i++) {
            JButton button = new JButton(movies.get(i).getTitle());
            button.setPreferredSize(new Dimension(200, 100));
            panel.add(button, BorderLayout.CENTER);
            validate();
        }

        panel.setVisible(true);

        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnLogOut = new javax.swing.JButton();
        BtnProfile = new javax.swing.JButton();
        LblWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnLogOut.setText("Log Out");
        BtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogOutActionPerformed(evt);
            }
        });

        BtnProfile.setText("My Profile");
        BtnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProfileActionPerformed(evt);
            }
        });

        LblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblWelcome.setText("Welcome !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(LblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BtnProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnLogOut)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLogOut)
                    .addComponent(BtnProfile)
                    .addComponent(LblWelcome))
                .addContainerGap(350, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogOutActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnLogOutActionPerformed

    private void BtnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProfileActionPerformed
        MyProfile m = new MyProfile(user);
        m.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnProfileActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogOut;
    private javax.swing.JButton BtnProfile;
    private javax.swing.JLabel LblWelcome;
    // End of variables declaration//GEN-END:variables
}
